name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@v1.0.0
      with:
        keystore: /u3+7QAAAAIAAAABAAAAAQAJYXBwdXBkYXRlAAABZ32+z3MAAAUBMIIE/TAOBgorBgEEASoCEQEBBQAEggTpUs1q1ShDvt0/MP1ujDB10h2+glDaDNY6oK0zCegkheVHVff0+lXsZteGXwSwW7mAW6JskYeZRxMqB19zy+9gvV4gkicoNjzCYqWrh2B3vE8ijKgHxGB4Wnf8jIRSuSuKSJdSoA8CuSeDnxdyxIQ9rUxcowLI43PVoJrLWoA73H5n6juxlkQYQ6OMdQBpCcX9fb8xeLPnVmqtSIAsm099MFf+EopHhQchR1Nuy50BKf+7/IZzMOiYyEett97F2uF+9K9SP7xCOaROvJIe+01R/Dbls9lTxNMYmU51HDyzvHDcNhNyzvRv6QU/5lcYPzAKl2LWUiInYO9NafcNCi9LGs2ZLibk4+JFIvsKvPfDsEkbg1BJ702XsNymPlzzTW90vJLGj3Tkm4zcyydUFX5BqYUkWySgvjrVYrwnvQAFDruFpqwH4454hL6ZRFrFePz9r2c+YTiBAI3J3QQkHFQgjLpAKT7DfWMy5DrrxQ+d30zo/i5PJEfPpeaseluPANcIaLctfOsXruM2Fg4iWrebmC8H/Ay1H9SkbUqFpwZLGAIpZaY+Hhqn5YmS9rgXObHjNExmlQSD+eVPg8SN4y7RyqATBoelqVrrciclmgsD4szeVz89vie4Upbu8H4oyJohiq+gnXjVDRWwP9SO0s99dup1iJWhheT1laVtFtfxhhol03cI0ckkU8cRm45Bza3KOPNmLe5HFMmhjO2+eOJ4nYZOmjKLTu177k8xbazcXmnlTWxljkhfddX+tWOGnKqB28S6n7zPCLE+etP/jjt9OSABO7QFKMcMFxlL9IEjO4ycYE5PMkABsTGGypXNTn2trc8NuFQoNRPEryjO4vTLtIM6Xv0Ws/yBIp1Yn1VdHjl8iGoXEV5rSeWzxAO1SaALztG72W3rVeAxBd+VnSyebN0KIHhlC0Y7upkmyYGOktJmt49Xm2fwuiSIoHM1HLMxrT2dtgvysDqMCe6wVTbJ+jTa0SUoNprpHjMH750eXWkiiD6HSryfZlNzDl0TonPPPaui2ZG5NtQCCn4gdWGgzs6rSMpjfGhZiLkLMxVYv1gEGBkS5EfXTgF8KCP+FES/N3GZAJ/iRQgauSElwV3CREPhEAUqXkAJoOs5QiiwwNoYdgzlE95Qxp8fD1WSXXn95+7MpN50mfrzxe2nxbIh4oRMwvQKsJv59FImecTNgUq4sxKjGV4nk3wTzUdUcXUIEg6IgyJuQ0gcsmOGIBq7fPqk0Ds8HbTg+wd5NNW3Upie4udDsgWoR9pobnykoB3y/xnJoMz3MHZBXN5tD6Y3ccHK/mZgJLLDYUhviVszJgSC+4GlS10JizBpKed4bWgS4/iwgBhvErIy6fYeWK+lsUBqx1FAYUqsNmRdU+GovpxT447TKlSW/qvk44ffKnTUx+rLizCVN+cV8xN6a+tL/Mr7nn2fyHICZf2U8Xy0WvHXVFfoEwxKFVdDxuAINNHkiohyPrfdsAq0MtVFnqic4neWvv8iSD9RAUo1mz2Lov6SpRPdtYpJFvkf2skSoTcbzh9Clrh9ntvj2shU7uUtGtaVZca+AenKH7+W496xeeAidqQuzfhmnjuQk0oCTaFylkNYbAmgSKp5waivtRKs8XqIychKzpDmMxKlHirtjP0rGDqu08kPRnPDXBbvSyrgTuefFvw0akXfAAAAAQAFWC41MDkAAALDMIICvzCCAaegAwIBAgIEQK5M3DANBgkqhkiG9w0BAQsFADAQMQ4wDAYDVQQDEwVhemhvbjAeFw0xODEyMDUwOTQxNTZaFw00MzExMjkwOTQxNTZaMBAxDjAMBgNVBAMTBWF6aG9uMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApwvHEwC/x3hfnIsFA4scIsQygpuyqlNEHtO2rf2+krIvinE0bQzrRVS/0GApVw7+isVHePK2xbJOya3fFQQuML60NjRf+2t8O98IfUv2w9IGO+I53IJEhafmngaTGKAZX6lgj1KA21Duyzo5QQZvzON4W3kfcoM8bBjwptZ82QIBbWz/sdS6NSqa4rG5AW7dKruIJDjQdm8Drm8P81KyXx5bmAN3u4bqU8cMvNclC2TkbVyZNqUhW60MUgibQZbyJIV96+dQ1FH+rd3KpmNbH0Us3oa6lXhXQozPUvi+pwnbrTGXKFhCUhFzlUOa5m77SQbtnzMAvhTVHa4GDuQ59QIDAQABoyEwHzAdBgNVHQ4EFgQUWn7lpS6oC8pzbUKhWVptPamDoT8wDQYJKoZIhvcNAQELBQADggEBAGtAiF3UfqDNFGscjmvvQq5N98MaYWdBwNOe5hBmfhSn1KIHRcq6C0rfaCimcs+eoLUxlu/XXUJtOl2tSEwS6mxtt+OuWoyhdMG+qjEdUhirmZXkwg+HaS2Zabsxoe4HHQfUlbzItHhtVN+LxsASBDqNgxofFRoobQtIHEzichjUH4nrW+/y0NDNIE0Tt4H2XusjGlGKgPmi2iKaJfpWruDvkYR8YPQGtSQU43PF8clmEBxQPBnqTC7de2XlUcuMIq0aIThxsOnAbBaNCCH21or6jTQP2fAVEWHv5sQ1p3NPMjJ08n9B9XzZ4z8VDnsUT0zJxoO1cHa+t9JrvXCW/bFbJqrRm3uGe67m11nZ2gnRirmYUQ==
        keystore_password: 123456
        key_alias: appUpdate
        key_password: 123456
